### ISSUE TITLE
Fix dot plot to line plot 

### ISSUE THREAD

**Issue by cfelletter** [usbr/Process-MTOM-R#6]

**Comment by eaalexander** [comment]
Done! 

 p <- scen_res %>%
    # dplyr::filter(Variable == variable) %>%
    dplyr::filter(Year >= startyr) %>% #filter year
    dplyr::filter(Year <= filteryrlessorequal) %>% #filter year
    dplyr::group_by(Scenario, Year) %>%
    dplyr::summarise(Value = mean(Value)) %>%
    ggplot(aes(x = factor(Year), y = Value, color = Scenario,group=Scenario)) + 
    geom_line() +
    geom_point() +
    labs(title = paste("Mean",variable,startyr,"-",filteryrlessorequal), 
         y = y_lab, x = "Year") 
  print(p)
