### ISSUE TITLE
Get info on geom_boxplot() 

### ISSUE THREAD

**Issue by cfelletter** [usbr/Process-MTOM-R#7]
Get info on geom_boxplot() - what are whiskers? What are lines (90/95)? What are outliers?

**Comment by cfelletter** [comment]
@rabutler-usbr and @sbaker2423 do you think we should be using the custom_boxplot()/Balaji code rather than geom_boxplot()? Just want to be consistent across all applications. Either way Elliot suggested adding note at the bottom of plots with the info on what the whiskers mean.

**Comment by rabutler-usbr** [comment]
`geom_boxplot()` uses 1.5 * IQR for the whiskers. I've created custom ggplot code with a geom that goes to the 5th-95th percentiles by default and will take in arguments for different percentiles. If you don't have that, then I can provide it. 

I like Elliot's suggestion that it should be included in the caption of the plot. I'm definitely not always good about being consistent, as it's easier to use the default geom, than find my custom code. I'm planning on adding the geom to the CRSSIO package, so then it will be a little easier to use it more frequently.

**Comment by sbaker2423** [comment]
Agreed. In the past, I have had notes on all of my boxplot figures
describing the properties of the whiskers, etc.

**Comment by cfelletter** [comment]
Thanks @rabutler-usbr let me know where I can find it in CRSSIO and I'll change the generic CRSS & MTOM plots to it and add a caption.

**Comment by rabutler-usbr** [comment]
Filed as an enhancement to CRSSIO (https://github.com/BoulderCodeHub/CRSSIO/issues/51)

Will add this in for the next CRSSIO release.

**Comment by rabutler-usbr** [comment]
@cfelletter don't the monthly and annual files need to source the new file, and rely on `stat_boxplot_custom()` instead of `geom_boxplot()`?

**Comment by cfelletter** [comment]
@rabutler-usbr Good catch. I was trying to propagate 6 changes through 4 files and this one got mixed. Surprised it didn't show up when I ran everything but I must have sourced that code already in my session.
