### ISSUE TITLE
How to change the y-axis line length

### ISSUE THREAD

**Issue by M0zby** [usbr/Process-MTOM-R#8]
Hello,
I am quite new in programming,
I am using R to plot violin plots using ggplots.
the Y-axis fill up the whole page (default page settings) and thus my plot is going upwards and the data is kind of thinned down and stretched.
How can I make the axis line shorter, without changing the ylim.
here is the coding line i used for violin plot:

vp1 <- ggplot(R1, aes(x=variable, y=value)) + 
  geom_violin(trim=FALSE, fill="#A4A4A4")+
  geom_boxplot(width=0.1, fill="white")+
  labs(title="", x="", y = "")+ 
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x))) +
  theme(panel.grid.major.y = element_line(color="grey", size=.1), panel.background = element_blank(),
        axis.text.x = element_text(color="black", size=12, angle=90, vjust=0.49, hjust=0),
        axis.text.y = element_text(color="black", size=11), axis.line = element_line(colour = "black"),
        axis.title.y= element_text(color="black", size=12, vjust=3))

I tried using annotate but that doesnt work with my plot. it just add a line rather than changing or shortening the y-axis line !

Does anyone know how to help with this issue?
Many thanks,

**Comment by rabutler-usbr** [comment]
@M0zby: for more generic R questions, I'd recommend using stackoverflow.com; this specific GitHub repository is for a very specific use of R. It's also useful if you provide a working minimum reproducible example. In the code you provided, we don't know what `R1` is, so we can't run your code. 

All that being said, you might check out `ggsave()`. If I understand your issue correctly, you want a different shaped rectangular plotting area? So you can change the `width` and `height` arguments to do this. You can use `?ggsave()` in the R-console to see how to use it.
